mongo:
  connectionUrl: MONGODB_URI
  reconnectInterval: MONGODB_RECONNECT_INTERVAL
email:
  shouldSendConfirmation: SEND_EMAIL_CONFIRMATION
  server:
    user: EMAIL_USER_NAME
    pass: EMAIL_PASS
  login:
    secretKey: JWT_TOKEN_SECRET
    tokenExpiry: LOGIN_TOKEN_EXPIRY
  expirationTime: EMAIL_EXPIRATION_TIME
  verificationBaseURL: EMAIL_VERIFICATION_BASE_URL
service:
  verifyToken: PROTECT_SERVICES_BY_TOKEN